//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKlinkGUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MKlinkGUI.Resources.Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 管理员权限 的本地化字符串。
        /// </summary>
        public static string Home_Btn_Admin {
            get {
                return ResourceManager.GetString("Home_Btn_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        public static string Home_Btn_OpenFile {
            get {
                return ResourceManager.GetString("Home_Btn_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string Home_Btn_OpenFolder {
            get {
                return ResourceManager.GetString("Home_Btn_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        public static string Home_Btn_Run {
            get {
                return ResourceManager.GetString("Home_Btn_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模式: 的本地化字符串。
        /// </summary>
        public static string Home_Mode {
            get {
                return ResourceManager.GetString("Home_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string Home_Mode_File {
            get {
                return ResourceManager.GetString("Home_Mode_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string Home_Mode_Folder {
            get {
                return ResourceManager.GetString("Home_Mode_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录链接 /J 的本地化字符串。
        /// </summary>
        public static string Home_Mode_FolderLinkRadio {
            get {
                return ResourceManager.GetString("Home_Mode_FolderLinkRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬链接 /H 的本地化字符串。
        /// </summary>
        public static string Home_Mode_HardLinkRadio {
            get {
                return ResourceManager.GetString("Home_Mode_HardLinkRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 符号链接 /D 的本地化字符串。
        /// </summary>
        public static string Home_Mode_SymbolicLinkRadio {
            get {
                return ResourceManager.GetString("Home_Mode_SymbolicLinkRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源位置: 的本地化字符串。
        /// </summary>
        public static string Home_Path_SourcePath {
            get {
                return ResourceManager.GetString("Home_Path_SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员权限下拖放可能失效
        ///可以使用复制粘贴获取文件位置 的本地化字符串。
        /// </summary>
        public static string Home_Path_SourcePath_Tip {
            get {
                return ResourceManager.GetString("Home_Path_SourcePath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择源位置 的本地化字符串。
        /// </summary>
        public static string Home_Path_SourcePath_Value {
            get {
                return ResourceManager.GetString("Home_Path_SourcePath_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标位置: 的本地化字符串。
        /// </summary>
        public static string Home_Path_TargetPath {
            get {
                return ResourceManager.GetString("Home_Path_TargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员权限下拖放可能失效
        ///可以使用复制粘贴获取文件位置 的本地化字符串。
        /// </summary>
        public static string Home_Path_TargetPath_Tip {
            get {
                return ResourceManager.GetString("Home_Path_TargetPath_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标位置 的本地化字符串。
        /// </summary>
        public static string Home_Path_TargetPath_Value {
            get {
                return ResourceManager.GetString("Home_Path_TargetPath_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Nav_Setting {
            get {
                return ResourceManager.GetString("Nav_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string Set_About {
            get {
                return ResourceManager.GetString("Set_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Set_Theme {
            get {
                return ResourceManager.GetString("Set_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色设置 的本地化字符串。
        /// </summary>
        public static string Set_Theme_ColorPreferences {
            get {
                return ResourceManager.GetString("Set_Theme_ColorPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string Set_Theme_ColorPreferences_Dark {
            get {
                return ResourceManager.GetString("Set_Theme_ColorPreferences_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string Set_Theme_ColorPreferences_Light {
            get {
                return ResourceManager.GetString("Set_Theme_ColorPreferences_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置 的本地化字符串。
        /// </summary>
        public static string Set_Theme_i18n {
            get {
                return ResourceManager.GetString("Set_Theme_i18n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @todo 需要重启 的本地化字符串。
        /// </summary>
        public static string Set_Theme_i18n_RestartToApply {
            get {
                return ResourceManager.GetString("Set_Theme_i18n_RestartToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MKlinkGUI 的本地化字符串。
        /// </summary>
        public static string Uni_MKlinkGUI {
            get {
                return ResourceManager.GetString("Uni_MKlinkGUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.0 的本地化字符串。
        /// </summary>
        public static string Uni_Version {
            get {
                return ResourceManager.GetString("Uni_Version", resourceCulture);
            }
        }
    }
}
